### ISSUE TITLE
Feature requests for Grial UI Kit

### ISSUE THREAD

**Issue by jpbrocca** [UXDivers/Grial-UI-Kit-Bugs-1.1.0#3]
Hi! The idea is to use this to request new features for Grial.
Please add your suggestions to this thread, that will help us making Grial a better product for you and other colleagues.

Here's the list so far -not prioritized yet-:

- Make Grial fully compatible with Xamarin Forms 2.0
- Add Windows Phone support
- Add Windows apps support
- Add better support for tablets

**Comment by Laumania** [comment]
It's not to take over your issue list, I just thought it might be easier to show you :)

I suggest a label is created called "feature-request" and then each individual request is it's own issue with that label attached.

This way, things are kept separated. By having ONE issue like this, you will very quickly loose the overview, as people might discus all sorts of things in here :)

Just a suggestion, if you don't like it - feel free to just close the 4 issues I just created :)

PS: Another benefit of having separated issues, is that you can close one at the time when you implement them and sort by the label in the overview of issues and easily see what users suggest.

**Comment by jpbrocca** [comment]
Awesome! Great suggestion!

Thank you very much! :)
ᐧ

2015-12-04 9:35 GMT-03:00 Mads Laumann <notifications@github.com>:

> It's not to take over your issue list, I just thought it might be easier
> to show you :)
>
> I suggest a label is created called "feature-request" and then each
> individual request is it's own issue with that label attached.
>
> This way, things are kept separated. By having ONE issue like this, you
> will very quickly loose the overview, as people might discus all sorts of
> things in here :)
>
> Just a suggestion, if you don't like it - feel free to just close the 4
> issues I just created :)
>
> PS: Another benefit of having separated issues, is that you can close one
> at the time when you implement them and sort by the label in the overview
> of issues and easily see what users suggest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UXDivers/Grial-UI-Kit-Bugs-1.1.0/issues/3#issuecomment-161956423>
> .
>



--

**Comment by Laumania** [comment]
We should close this issue now that we have them as separate issues :)
